targets:
  $default:
    builders:
      freezed:
        options:
          format: false
      json_serializable:
        options:
          field_rename: snake
          include_if_null: false
          