name: Flutter Web Deploy

on:
  push:
    branches: [ main ]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build web
        run: flutter build web --release -t "lib/app/entrypoints/main_prod.dart" --base-href /${GITHUB_REPOSITORY#*/}/
        
      - name: Create deployment directory
        run: |
          mkdir deployment
          cp -r build/web/* deployment/
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web/
